import * as Blockly from "blockly";

const GRAMMAR_TOOLTIPS: Record<string, string> = {
  program: "Grammar: program ::= dec | functor fctbind | signature sigbind",
  program_functor: "Grammar: program ::= functor fctbind",
  program_signature: "Grammar: program ::= signature sigbind",
  program_child: "Grammar: program item ::= dec | functor fctbind | signature sigbind",
  program_child_container: "Grammar: program ::= program item...",

  fctbind_plain: "Grammar: fctbind ::= fctid (strid : sigexp) = strexp",
  fctbind_opened: "Grammar: fctbind ::= fctid (spec) = strexp",
  fctbind_nested: "Grammar: fctbind ::= fctbind and fctbind",
  fctbind_child: "Grammar: fctbind row ::= fctbind",
  fctbind_child_container: "Grammar: fctbind ::= fctbind and ...",
  sigbind_single: "Grammar: sigbind ::= sigid = sigexp",
  sigbind_nested: "Grammar: sigbind ::= sigbind and sigbind",
  sigbind_child: "Grammar: sigbind row ::= sigbind",
  sigbind_child_container: "Grammar: sigbind ::= sigbind and ...",

  con_int: "Grammar: scon ::= int",
  con_string: "Grammar: scon ::= string",
  con_char: "Grammar: scon ::= char",
  con_float: "Grammar: scon ::= real",
  con_word: "Grammar: scon ::= word",

  id_id: "Grammar: id ::= alphanumeric-id | symbolic-id",
  id_long_id: "Grammar: longid ::= strid . ... . id",
  id_var: "Grammar: vid ::= id",
  id_long_var: "Grammar: longvid ::= strid . ... . vid",
  id_lab: "Grammar: lab ::= id | number",
  long_child_var: "Grammar: longvid segment ::= strid",
  long_child_var_container: "Grammar: longvid ::= strid . ... . vid",

  exp_bound: "Grammar: exp ::= scon | longvid",
  exp_application: "Grammar: exp ::= exp exp",
  exp_infix_application: "Grammar: exp ::= exp vid exp",
  exp_sequence: "Grammar: exp ::= (exp ; ... ; exp)",
  sequence_child: "Grammar: expression sequence item ::= exp",
  sequence_child_container: "Grammar: exp sequence ::= exp ; ...",
  exp_parentheses: "Grammar: exp ::= (exp)",
  exp_let_in_end: "Grammar: exp ::= let dec in exp end",
  exp_with_type: "Grammar: exp ::= exp : ty",
  exp_raise: "Grammar: exp ::= raise exp",
  exp_handle: "Grammar: exp ::= exp handle match",
  exp_andalso: "Grammar: exp ::= exp andalso exp",
  exp_orelse: "Grammar: exp ::= exp orelse exp",
  exp_if_else: "Grammar: exp ::= if exp then exp else exp",
  exp_while_do: "Grammar: exp ::= while exp do exp",
  exp_fn: "Grammar: exp ::= fn match",
  exp_case: "Grammar: exp ::= case exp of match",
  match: "Grammar: match ::= mrule | mrule | match",
  matchs: "Grammar: mrule ::= pat => exp",
  match_child: "Grammar: match item ::= mrule",
  match_child_container: "Grammar: match ::= mrule | ...",
  exp_list: "Grammar: exp ::= [exp, ..., exp]",
  list_child: "Grammar: list item ::= exp",
  list_child_container: "Grammar: exp list ::= exp, ...",
  exp_tuple: "Grammar: exp ::= (exp, ..., exp)",
  tuple_child: "Grammar: tuple item ::= exp",
  tuple_child_container: "Grammar: tuple ::= exp, ...",
  exp_record_select: "Grammar: exp ::= #lab",
  exp_record: "Grammar: exp ::= {exprow}",
  exprow: "Grammar: exprow ::= lab = exp | lab = exp, exprow",
  record_child: "Grammar: expression record item ::= exprow",
  record_child_container: "Grammar: exprow ::= exprow, ...",
  exprow_child: "Grammar: expression row item ::= lab = exp",
  exprow_child_container: "Grammar: exprow ::= lab = exp, ...",
  let_in_end_child: "Grammar: let body item ::= exp",
  let_in_end_child_container: "Grammar: let body ::= exp ; ...",

  pat_wildcard: "Grammar: pat ::= _",
  pat_id: "Grammar: pat ::= scon | vid",
  pat_long_id: "Grammar: pat ::= longvid pat",
  pat_infix: "Grammar: pat ::= pat vid pat",
  pat_parentheses: "Grammar: pat ::= (pat)",
  pat_type_annotation: "Grammar: pat ::= pat : ty",
  pat_layered: "Grammar: pat ::= vid as pat",
  pat_record: "Grammar: pat ::= {patrow}",
  patrow_wildcard: "Grammar: patrow ::= ...",
  patrow_lab_pat: "Grammar: patrow ::= lab = pat",
  patrow_variable: "Grammar: patrow ::= vid [: ty] [as pat]",
  pat_record_child: "Grammar: pattern row item ::= patrow",
  pat_record_child_container: "Grammar: patrow ::= patrow, ...",
  pat_tuple: "Grammar: pat ::= (pat, ..., pat)",
  pat_tuple_child: "Grammar: tuple pattern item ::= pat",
  pat_tuple_child_container: "Grammar: tuple pattern ::= pat, ...",
  pat_list: "Grammar: pat ::= [pat, ..., pat]",
  pat_list_child: "Grammar: list pattern item ::= pat",
  pat_list_child_container: "Grammar: list pattern ::= pat, ...",

  typ_var: "Grammar: ty ::= 'a",
  typ_constructor: "Grammar: ty ::= tyseq longtycon",
  constructor_child: "Grammar: type constructor argument ::= ty",
  constructor_child_container: "Grammar: tyseq ::= ty | (ty, ..., ty)",
  typ_parentheses: "Grammar: ty ::= (ty)",
  typ_function: "Grammar: ty ::= ty -> ty",
  typ_primtv: "Grammar: ty ::= int | real | bool | string | char | unit | word",
  typ_list: "Grammar: ty ::= ty list",
  typ_tuple: "Grammar: ty ::= ty * ... * ty",
  typ_tuple_child: "Grammar: tuple type item ::= ty",
  typ_tuple_child_container: "Grammar: tuple type ::= ty * ...",
  typ_record: "Grammar: ty ::= {tyrow}",
  typ_record_child: "Grammar: type row item ::= lab : ty",
  typ_record_child_container: "Grammar: tyrow ::= lab : ty, ...",

  str_identifier: "Grammar: strexp ::= longstrid",
  str_structure: "Grammar: strexp ::= struct dec end",
  str_local_declaration: "Grammar: strexp ::= let dec in strexp end",
  str_transparent_annotation: "Grammar: strexp ::= strexp : sigexp",
  str_opaque_annotation: "Grammar: strexp ::= strexp :> sigexp",
  str_functor_application_str: "Grammar: strexp ::= fctid (strexp)",
  str_functor_application_dec: "Grammar: strexp ::= fctid (dec)",
  sig_id: "Grammar: sigexp ::= sigid",
  sig_signature: "Grammar: sigexp ::= sig spec end",
  sig_refinement: "Grammar: sigexp ::= sigexp where type typrefin",
  typrefin_single: "Grammar: typrefin ::= tyvarseq longtycon = ty",
  typrefin_nested: "Grammar: typrefin ::= typrefin and typrefin",
  typrefin_child: "Grammar: type refinement item ::= typrefin",
  typrefin_child_container: "Grammar: typrefin ::= typrefin and ...",

  spec_value: "Grammar: spec ::= val valdesc",
  valdesc_single: "Grammar: valdesc ::= vid : ty",
  valdesc_nested: "Grammar: valdesc ::= valdesc and valdesc",
  valdesc_child: "Grammar: value description item ::= valdesc",
  valdesc_child_container: "Grammar: valdesc ::= valdesc and ...",
  spec_type: "Grammar: spec ::= type typdesc",
  spec_equality_type: "Grammar: spec ::= eqtype typdesc",
  spec_type_abbreviation: "Grammar: spec ::= type typbind",
  typdesc_single: "Grammar: typdesc ::= tyvarseq tycon",
  typdesc_nested: "Grammar: typdesc ::= typdesc and typdesc",
  typdesc_child: "Grammar: type description item ::= typdesc",
  typdesc_child_container: "Grammar: typdesc ::= typdesc and ...",
  spec_datatype: "Grammar: spec ::= datatype datdesc",
  spec_datatype_replication: "Grammar: spec ::= datatype tycon = datatype longtycon",
  datdesc_single: "Grammar: datdesc ::= tyvarseq tycon = condesc",
  datdesc_nested: "Grammar: datdesc ::= datdesc and datdesc",
  datdesc_child: "Grammar: datatype description item ::= datdesc",
  datdesc_child_container: "Grammar: datdesc ::= datdesc and ...",
  condesc_single: "Grammar: condesc ::= vid [of ty]",
  condesc_nested: "Grammar: condesc ::= condesc | condesc",
  condesc_child: "Grammar: constructor description item ::= condesc",
  condesc_child_container: "Grammar: condesc ::= condesc | ...",
  spec_exception: "Grammar: spec ::= exception exndesc",
  exndesc_single: "Grammar: exndesc ::= vid [of ty]",
  exndesc_nested: "Grammar: exndesc ::= exndesc and exndesc",
  exndesc_child: "Grammar: exception description item ::= exndesc",
  exndesc_child_container: "Grammar: exndesc ::= exndesc and ...",
  spec_structure: "Grammar: spec ::= structure strdesc",
  strdesc_single: "Grammar: strdesc ::= strid : sigexp",
  strdesc_nested: "Grammar: strdesc ::= strdesc and strdesc",
  strdesc_child: "Grammar: structure description item ::= strdesc",
  strdesc_child_container: "Grammar: strdesc ::= strdesc and ...",
  spec_sequence: "Grammar: spec ::= spec ; spec",
  spec_child: "Grammar: specification item ::= spec",
  spec_child_container: "Grammar: spec ::= spec ; ...",
  spec_inclusion_sig: "Grammar: spec ::= include sigexp",
  spec_inclusion: "Grammar: spec ::= include sigid ... sigid",
  spec_inclusion_child: "Grammar: included signature item ::= sigid",
  spec_inclusion_child_container: "Grammar: include ::= sigid ...",
  spec_type_sharing: "Grammar: spec ::= spec sharing type longtycon = ... = longtycon",
  spec_type_sharing_child: "Grammar: shared type item ::= longtycon",
  spec_type_sharing_child_container: "Grammar: sharing type ::= longtycon = ...",

  dec_val: "Grammar: dec ::= val tyvarseq valbind",
  valbind: "Grammar: valbind ::= pat = exp | rec valbind | valbind and valbind",
  val_child: "Grammar: value binding item ::= valbind",
  val_child_container: "Grammar: valbind ::= valbind and ...",
  dec_fun: "Grammar: dec ::= fun tyvarseq fvalbind",
  funmatch_infix: "Grammar: funmatch ::= pat vid pat = exp",
  funmatch_infix_n_inhabitant: "Grammar: funmatch ::= pat vid pat pat... = exp",
  funmatch_nonfix: "Grammar: funmatch ::= vid pat... = exp",
  funmatch_more_row: "Grammar: fvalbind ::= funmatch | funmatch | fvalbind",
  funmatch_child: "Grammar: function match item ::= funmatch",
  funmatch_child_container: "Grammar: fvalbind ::= funmatch | ...",
  funmatch_infix_n_child: "Grammar: infix function argument ::= pat",
  funmatch_infix_n_child_container: "Grammar: infix function arguments ::= pat...",
  funmatch_nonfix_child: "Grammar: function argument ::= pat",
  funmatch_nonfix_child_container: "Grammar: function arguments ::= pat...",
  fun_child: "Grammar: function binding item ::= fvalbind",
  fun_child_container: "Grammar: fvalbind ::= fvalbind and ...",
  dec_structure: "Grammar: dec ::= structure strbind",
  strbind_single: "Grammar: strbind ::= strid [: sigexp] = strexp",
  strbind_nested: "Grammar: strbind ::= strbind and strbind",
  strbind_child: "Grammar: structure binding item ::= strbind",
  strbind_child_container: "Grammar: strbind ::= strbind and ...",
  dec_exception: "Grammar: dec ::= exception exnbind",
  exnbind: "Grammar: exnbind ::= vid [of ty]",
  exnbind_renaming: "Grammar: exnbind ::= vid = longvid",
  exnbind_more_inhabitants: "Grammar: exnbind ::= exnbind and exnbind",
  exnbind_more_child: "Grammar: exception binding item ::= exnbind",
  exnbind_more_child_container: "Grammar: exnbind ::= exnbind and ...",
  dec_type: "Grammar: dec ::= type typbind",
  dec_datatype_replication: "Grammar: dec ::= datatype tycon = datatype longtycon",
  dec_datatype_bind: "Grammar: dec ::= datatype datbind [withtype typbind]",
  dec_abstype: "Grammar: dec ::= abstype datbind [withtype typbind] with dec end",
  typbind: "Grammar: typbind ::= tyvarseq tycon = ty",
  typebind_more_inhabitants: "Grammar: typbind ::= typbind and typbind",
  typebind_more_child: "Grammar: type binding item ::= typbind",
  typebind_more_child_container: "Grammar: typbind ::= typbind and ...",
  datbind: "Grammar: datbind ::= tyvarseq tycon = conbind",
  databind_more_inhabitants: "Grammar: datbind ::= datbind and datbind",
  databind_more_child: "Grammar: datatype binding item ::= datbind",
  databind_more_child_container: "Grammar: datbind ::= datbind and ...",
  conbind: "Grammar: conbind ::= op vid [of ty]",
  conbind_more_inhabitants: "Grammar: conbind ::= conbind | conbind",
  conbind_more_child: "Grammar: constructor binding item ::= conbind",
  conbind_more_child_container: "Grammar: conbind ::= conbind | ...",
  dec_local: "Grammar: dec ::= local dec in dec end",
  dec_sequence: "Grammar: dec ::= dec ; dec",
  dec_seq_child: "Grammar: declaration sequence item ::= dec",
  dec_seq_child_container: "Grammar: dec ::= dec ; ...",
  dec_open: "Grammar: dec ::= open longstrid ... longstrid",
  dec_open_child: "Grammar: open declaration item ::= longstrid",
  dec_open_child_container: "Grammar: open ::= longstrid ...",
  dec_nonfix: "Grammar: dec ::= nonfix vid ... vid",
  dec_nonfix_child: "Grammar: nonfix declaration item ::= vid",
  dec_nonfix_child_container: "Grammar: nonfix ::= vid ...",
  dec_infix: "Grammar: dec ::= infix [digit] vid ... vid",
  dec_infix_child: "Grammar: infix declaration item ::= vid",
  dec_infix_child_container: "Grammar: infix ::= vid ...",
  dec_infixr: "Grammar: dec ::= infixr [digit] vid ... vid",
  dec_infixr_child: "Grammar: infixr declaration item ::= vid",
  dec_infixr_child_container: "Grammar: infixr ::= vid ...",

  exp_primtv_optr_arith: "Grammar: exp ::= primitive arithmetic operator",
  exp_primtv_optr_logic: "Grammar: exp ::= primitive logical operator",
  exp_primtv_optr_record: "Grammar: exp ::= #lab",
  exp_primtv_optr_list_hd: "Grammar: exp ::= hd exp",
  exp_primtv_optr_list_tail: "Grammar: exp ::= tl exp",
};

export function getGrammarTooltip(type: string): string | undefined {
  return GRAMMAR_TOOLTIPS[type];
}

export function applyGrammarTooltips(): void {
  for (const [type, tooltip] of Object.entries(GRAMMAR_TOOLTIPS)) {
    const blockDefinition = Blockly.Blocks[type] as any;
    if (!blockDefinition || blockDefinition.__grammarTooltipApplied) continue;
    const originalInit = blockDefinition.init;
    if (typeof originalInit !== "function") continue;
    blockDefinition.init = function (...args: unknown[]) {
      originalInit.apply(this, args);
      this.setTooltip(tooltip);
    };
    blockDefinition.__grammarTooltipApplied = true;
  }
}
