import * as Blockly from "blockly";
import { SML } from "../../sml";

SML.forBlock["program"] = function (block) {
  let comment =
    "(* " +
    "SML code generated by \nYETI (Yet [E/A]Another Transpiler Interface)" +
    " *) \n \n",
    value_add = "",
    code = "";

  for (let i = 0; i < block.itemCount_; i++) {
    value_add +=
      SML.valueToCode(block, "ADD" + i, SML.ORDER_NONE) + "\n";
  }

  code = comment + value_add;
  return code;
};

SML.forBlock["program_functor"] = function (block) {
  let fctbind = SML.valueToCode(
    block,
    "fctbind",
    SML.ORDER_NONE
  ),
    code = "functor " + fctbind + " \n";
  return [code, SML.ORDER_NONE];
};

SML.forBlock["program_signature"] = function (block) {
  let sigbind = SML.valueToCode(
    block,
    "sigbind",
    SML.ORDER_NONE
  ),
    code = "signature " + sigbind + " \n";
  return [code, SML.ORDER_NONE];
};
